### ISSUE TITLE
Adding Route Functionality

### ISSUE THREAD

**Issue by benmcrae5** [kara-krzystan/Team-Project-Wk15#18]
setting up /api/routes function

**Comment by P00KIEBEAR** [comment]
got login route link and schedule page route up

**Comment by P00KIEBEAR** [comment]
Still need to get schedule route to create and delete appt.

**Comment by P00KIEBEAR** [comment]
Updated schedule route

**Comment by benmcrae5** [comment]
Not sure why this wasn't "completed" sooner...
